name: rust_dart_ffi_protobuf
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Sacha <sacha.arbonel@hotmail.fr>

environment:
  sdk: '>=2.9.0-16.0.dev <3.0.0'

dependencies:
 protobuf: ^1.0.1
 ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  # ffi_tool: ^0.2.5
